name: Publish and Deploy

on:
  push:
    # TODO: remove before merge
    branches: [test/benchmarking]

    # TODO: uncomment before merge
    # branches: [main]

  # allows this job to be triggered via api
  repository_dispatch:
    types: [publish-event]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Publish to s3
        env:
          PUBLISH_CONTENTS_S3_BUCKET:  fast-react-static-renderer-artifacts
          APP_SUBPATH: react

          # TODO: remove before merge
          APP_VERSION: benchmarking
        run: |
          echo "running scripts/ci/publish.sh"
          ./scripts/ci/publish.sh

  # TODO: uncomment before merge
  # # https://github.com/bitovi/github-actions-bitops-ci-cd
  # deploy-build-tools:
  #   # only deploy if not pull request
  #   if: github.event_name != 'pull_request'
  #   needs: [publish]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy Stage
  #       uses: bitovi/github-actions-bitops-ci-cd@0.5.0
  #       with:
  #         github-token: ${{ secrets.OPERATIONS_REPO_TOKEN }}
  #         org: bitovi
  #         repo: fast-react-static-renderer-operations
  #         branch: main
  #         workflow: deploy-build-dev-trigger.yaml
